# Generated by Django 5.0.1 on 2024-01-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_bookinstance_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrow',
            new_name='borrower',
        ),
    ]
